stages:
  - deploy-modification-to-remote-gitlab
deploy-modification-to-remote-gitlab:
  stage:  deploy-modification-to-remote-gitlab
  environment: prod
  script:
    - apt install -y git 
    -  git remote set-url origin http://git.diagoriente.beta.gouv.fr:3001/root/diagoriente-advisor-v5.git
    - export GIT_SSL_NO_VERIFY=1
    - git checkout master
    - git filter-branch -f --env-filter "
       GIT_AUTHOR_NAME=' Mahdi Hellal' 
       GIT_AUTHOR_EMAIL='mahdihellal@gmail.com' 
       GIT_COMMITTER_NAME='Mahdi hellal' 
       GIT_COMMITTER_EMAIL='mahdihellal@gmail.com'
       " HEAD
    - git push -f http://mahdi:mahdi123456@git.diagoriente.beta.gouv.fr:3001/root/diagoriente-advisor-v5.git master-prod
  only:
    - master-prod
  when: always




